name: Deploy (staging)

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: integrity-staging
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set Airtable secrets (staging)
        run: |
          flyctl secrets set \
            AIRTABLE_BASE_ID="${{ secrets.AIRTABLE_BASE_ID_STAGING }}" \
            AIRTABLE_API_KEY="${{ secrets.AIRTABLE_API_KEY_STAGING }}" \
            --app integrity-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy to Fly (staging)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --config fly.staging.toml --remote-only
